### Auth apis

### sign up user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "ashik3@gmail.com",
  "password": "12345637"
}

### sign in user

POST http://localhost:3000/auth/signin
content-type: application/json

{
"email": "ashik3@gmail.com",
"password": "12345637"
}


### get all users with profile
GET http://localhost:3000/user
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc2hpazNAZ21haWwuY29tIiwiaWF0IjoxNzA3ODQ5NDkyLCJleHAiOjE3MDc4ODU0OTJ9.hZohbTOm2AkzAugOst1iukvyUYl-EfsgN1iU0uBnYmw


### create profile
POST http://localhost:3000/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc2hpazNAZ21haWwuY29tIiwiaWF0IjoxNzA3ODQ5NDkyLCJleHAiOjE3MDc4ODU0OTJ9.hZohbTOm2AkzAugOst1iukvyUYl-EfsgN1iU0uBnYmw

{
  "firstName": "Ashik Ahmmed",
  "lastName": "Shuvo",
  "phoneNumber": "+8801730959501",
  "address": "Nikunja 2, Dhaka"
}

### update profile

PUT http://localhost:3000/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc2hpazNAZ21haWwuY29tIiwiaWF0IjoxNzA3ODQ5NDkyLCJleHAiOjE3MDc4ODU0OTJ9.hZohbTOm2AkzAugOst1iukvyUYl-EfsgN1iU0uBnYmw

{
"phoneNumber": "+8801730999602"
}

### get my Profile
GET http://localhost:3000/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiZW1haWwiOiJhc2hpazNAZ21haWwuY29tIiwiaWF0IjoxNzA3ODQ5NDkyLCJleHAiOjE3MDc4ODU0OTJ9.hZohbTOm2AkzAugOst1iukvyUYl-EfsgN1iU0uBnYmw

